#application: illust-book-hrd
#version: 1
runtime: python27
api_version: 1
default_expiration: "1m"
threadsafe: yes

automatic_scaling:
  max_idle_instances: 1

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest

builtins:
- appstats: on

inbound_services:
- channel_presence

skip_files:
- skip_files/.*
- js/ipad/.git/.*
- .*DS_Store

handlers:
- url: /flash
  static_dir: flash

- url: /js
  static_dir: js

- url: /static_files
  static_dir: static_files
  expiration: "1d"

- url: /template
  static_dir: template
  expiration: "10m"

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /favicon.ico
  static_files: favicon_pochi.ico
  upload: favicon_pochi.ico
  expiration: "1d"

- url: /.*
  script: Main.application

